### ISSUE TITLE
convertFormat error

### ISSUE THREAD

**Issue by Sukis123** [girke-lab/ChemmineOB#22]
Dear chemmineOB developer,
I am trying to use convertFormat function to convert smiles format to InChI form, however, I got an error (see the attached picture). what is the problem? it seems that it doesn't support inchi. 
![image](https://user-images.githubusercontent.com/55191839/79230555-1063e400-7e65-11ea-9eda-74f132f2fa68.png)

many thanks in advance.

**Comment by khoran** [comment]
It seems to work for me. Can you tell me what operating system your on and the version of R, openbabel and ChemmineOB? Thanks.

**Comment by Sukis123** [comment]
Thank you very much for your reply. I am working with windows 10 64 bit, R version 3.6.2, openbabel 3.0.0, and ChemmineOB 1.24. 
I installed ChemmineOB package following the instruction on the website: https://www.bioconductor.org/packages/release/bioc/html/ChemmineOB.html

I installed the openbabel binary 3.0.0, do i need to set environment variables or to compile it ?

**Comment by khoran** [comment]
That version of ChemmineOB is not compatible with OpenBabel 3.0.0. There is a pre-release version of ChemmineOB (1.25.1) available that should work with it though. You can download it here: https://github.com/girke-lab/ChemmineOB/releases

You should not need to compile openbabel on windows. 

As this is a pre-release version, I have not yet tested it on windows. So if you run into any problems, just let me know and I'll work on the windows version more today.

**Comment by khoran** [comment]
Alternatively, you could just install OpenBabel 2.4.1 if you don't need any features from 3.0.0.
https://github.com/openbabel/openbabel/releases/tag/openbabel-2-4-1

**Comment by Sukis123** [comment]
Thanks a lot. after downloading ChemmineOB(1.25.1), how can I install this package?

**Comment by khoran** [comment]
If your using R Studio, you can go to "tool" -> "install packages". Then set the "install from" type to be "Package archive file". Then select the file you downloaded.

**Comment by Sukis123** [comment]
Many thanks. I just installed Openbabel 2.4.1, and then installed ChemmineOB package (1.24), but i got the same error. I have also tried it on other computers with the same result. it is quite weird.

**Comment by khoran** [comment]
I think I was mistaken. After reading some of my old notes (I've not dealt with the windows version for a few years), I remembered that the windows version of ChemmineOB is statically compiled against OpenBabel 2.3.2. That means that OpenBabel is embedded inside ChemmineOB, and it will just ignore whatever other version of OpenBabel is installed on your system. 

Also after testing on windows a bit just now, I can see that most other formats work just fine. I think the problem is that the Inchi format itself is structured a little differently than the other formats (each format is a dynamically loadable module), and it just doesn't work on windows at all in this context. I vaguely recall have problems with that format in the past. 

Sorry for the misdirection. I'll play with it a bit more myself, but I think the conclusion will be the same.

**Comment by Sukis123** [comment]
Never mind. Thanks a lot. 
For me, InChIKey doesn't work neither.

**Comment by khoran** [comment]
This old issue confirms it: https://github.com/girke-lab/ChemmineOB/issues/9#issuecomment-233056732. 
Note that the ChemmieR solution mentioned there is no longer supported.

**Comment by Sukis123** [comment]
Understand.

**Comment by khoran** [comment]
This might help:
https://github.com/CDK-R/rinchi/

**Comment by Sukis123** [comment]
Thanks for your suggestion. I will try.

**Comment by Sukis123** [comment]
Thanks a lot. i will try.

**Comment by Sukis123** [comment]
I am now working with ubuntu 18.04.4. I have installed openbable 3.0.0. However, I failed to install chemmineOB 1.25.1 package as you suggested. please see the attachment below:
![bash_openbabel](https://user-images.githubusercontent.com/55191839/79691669-43411a00-8261-11ea-8a9b-688eb98266dc.jpg)
![Snipaste_2020-04-19_16-44-30](https://user-images.githubusercontent.com/55191839/79691678-4cca8200-8261-11ea-8049-88c1cd4714ee.jpg)
![Snipaste_2020-04-19_17-09-53](https://user-images.githubusercontent.com/55191839/79691682-548a2680-8261-11ea-8c02-50a2c29a9f01.jpg)

**Comment by khoran** [comment]
I'm not too familiar with "snaps", they may be putting their files in non-standard directories which will not be automatically found by R. Do you know what directory the snap was installed into? Can you give me a list of directories just under the openbabel snap directory? If I can understand the file structure more, I can give you some build options to specify the correct locations. Read the INSTALL file for some details. 

Ideally, it should be installed from a .deb file, using just "apt-get install openbabel". Now for unbuntu 18, only 2.3.2 is available. But it looks like ubuntu 20 has 3.0.0 packaged. Don't know if that is an option for you.

**Comment by Sukis123** [comment]
Many thanks for your reply!
I have successfully compiled Openbabel 3.0.0 in Linux mint, but I still got the same problem.
I just unziped openbabel in the home directory, created a build folder in the home directory, and compiled openbabel following the instruction. https://open-babel.readthedocs.io/en/latest/Installation/install.html#compiling-open-babel

the obutil.h file is under the openbabel folder.
see the attachment.
![image](https://user-images.githubusercontent.com/55191839/80010524-d0d37280-84ca-11ea-92c5-359533791fdd.png)


is there anything wrong?

**Comment by khoran** [comment]
You have to run "make install" also. Be default that will install the files under /usr/local/. That step will add the obutil.h file (and probably some others) to the final installation.

**Comment by Sukis123** [comment]
yes, i have done "make install" as well. the obutil.h file is there.
![image](https://user-images.githubusercontent.com/55191839/80012136-201aa280-84cd-11ea-8bc7-a01625d0831f.png)

**Comment by khoran** [comment]
Try the command
`R CMD INSTALL --configure-args='--with-openbabel-include=/usr/local/include/openbabel3/ --with-openbabel-lib=/usr/local/lib  '  ChemmineOB_1.25.1.tar.gz`

For the lib option, you may need to add a subdirectory to that or not, I'm not sure. See if /usr/local/lib/openbabel3 exists and if so use it.

**Comment by Sukis123** [comment]
![image](https://user-images.githubusercontent.com/55191839/80021176-6aeee700-84da-11ea-8050-514627012cdd.png)
there is openbabel folder under lib. I have tried with this code. but i got the following error.
sukis@sukis-virtual-machine:~$ sudo R CMD INSTALL --configure-args='--with-openbabel-include=/usr/local/include/openbabel3/ --with-openbabel-lib=/usr/local/lib/openbabel/3.0.0/ ' ChemmineOB_1.25.1.tar.gz
* installing to library ‘/home/sukis/R/x86_64-pc-linux-gnu-library/3.6’
* installing *source* package ‘ChemmineOB’ ...
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/sukis/R/x86_64-pc-linux-gnu-library/3.6/BH/include" -I"/home/sukis/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"  -I/usr/local/include/openbabel3/  -I/usr/include/eigen3  -DUSE_BOOST -DHAVE_EIGEN -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-V28x5H/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ChemmineOB.cpp -o ChemmineOB.o
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBUnitCell_UnwrapCartesianNear__SWIG_0(SEXP, SEXP, SEXP, SEXP)’:
ChemmineOB.cpp:11698:95: error: ‘class OpenBabel::OBUnitCell’ has no member named ‘UnwrapCartesianNear’
      else { arg3 = *(reinterpret_cast< OpenBabel::vector3 * >(argp3)); }  }  result = (arg1)->UnwrapCartesianNear(arg2,arg3);
                                                                                               ^~~~~~~~~~~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBUnitCell_UnwrapCartesianNear__SWIG_1(SEXP, SEXP, SEXP, SEXP)’:
ChemmineOB.cpp:11718:51: error: ‘const class OpenBabel::OBUnitCell’ has no member named ‘UnwrapCartesianNear’
   result = ((OpenBabel::OBUnitCell const *)arg1)->UnwrapCartesianNear(arg2,arg3);
                                                   ^~~~~~~~~~~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBUnitCell_UnwrapFractionalNear__SWIG_0(SEXP, SEXP, SEXP, SEXP)’:
ChemmineOB.cpp:11737:95: error: ‘class OpenBabel::OBUnitCell’ has no member named ‘UnwrapFractionalNear’
      else { arg3 = *(reinterpret_cast< OpenBabel::vector3 * >(argp3)); }  }  result = (arg1)->UnwrapFractionalNear(arg2,arg3);
                                                                                               ^~~~~~~~~~~~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBUnitCell_UnwrapFractionalNear__SWIG_1(SEXP, SEXP, SEXP, SEXP)’:
ChemmineOB.cpp:11757:51: error: ‘const class OpenBabel::OBUnitCell’ has no member named ‘UnwrapFractionalNear’
   result = ((OpenBabel::OBUnitCell const *)arg1)->UnwrapFractionalNear(arg2,arg3);
                                                   ^~~~~~~~~~~~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBUnitCell_MinimumImageCartesian__SWIG_0(SEXP, SEXP, SEXP)’:
ChemmineOB.cpp:11771:95: error: ‘class OpenBabel::OBUnitCell’ has no member named ‘MinimumImageCartesian’
      else { arg2 = *(reinterpret_cast< OpenBabel::vector3 * >(argp2)); }  }  result = (arg1)->MinimumImageCartesian(arg2);
                                                                                               ^~~~~~~~~~~~~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBUnitCell_MinimumImageCartesian__SWIG_1(SEXP, SEXP, SEXP)’:
ChemmineOB.cpp:11786:51: error: ‘const class OpenBabel::OBUnitCell’ has no member named ‘MinimumImageCartesian’
   result = ((OpenBabel::OBUnitCell const *)arg1)->MinimumImageCartesian(arg2);
                                                   ^~~~~~~~~~~~~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBUnitCell_MinimumImageFractional__SWIG_0(SEXP, SEXP, SEXP)’:
ChemmineOB.cpp:11800:95: error: ‘class OpenBabel::OBUnitCell’ has no member named ‘MinimumImageFractional’
      else { arg2 = *(reinterpret_cast< OpenBabel::vector3 * >(argp2)); }  }  result = (arg1)->MinimumImageFractional(arg2);
                                                                                               ^~~~~~~~~~~~~~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBUnitCell_MinimumImageFractional__SWIG_1(SEXP, SEXP, SEXP)’:
ChemmineOB.cpp:11815:51: error: ‘const class OpenBabel::OBUnitCell’ has no member named ‘MinimumImageFractional’
   result = ((OpenBabel::OBUnitCell const *)arg1)->MinimumImageFractional(arg2);
                                                   ^~~~~~~~~~~~~~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBAtom_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:17314:109: error: ‘const class OpenBabel::OBAtom’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBAtom * >(argp1); result = (bool)((OpenBabel::OBAtom const *)arg1)->IsPeriodic();
                                                                                                             ^~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBBond_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:17799:109: error: ‘const class OpenBabel::OBBond’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBBond * >(argp1); result = (bool)((OpenBabel::OBBond const *)arg1)->IsPeriodic();
                                                                                                             ^~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBMol_SetPeriodicMol__SWIG_0(SEXP, SEXP)’:
ChemmineOB.cpp:19080:107: error: ‘class OpenBabel::OBMol’ has no member named ‘SetPeriodicMol’
    arg1 = reinterpret_cast< OpenBabel::OBMol * >(argp1); arg2 = LOGICAL(value)[0] ? true : false; (arg1)->SetPeriodicMol(arg2);
                                                                                                           ^~~~~~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBMol_SetPeriodicMol__SWIG_1(SEXP)’:
ChemmineOB.cpp:19086:66: error: ‘class OpenBabel::OBMol’ has no member named ‘SetPeriodicMol’
    arg1 = reinterpret_cast< OpenBabel::OBMol * >(argp1); (arg1)->SetPeriodicMol(); r_ans = R_NilValue; vmaxset(r_vmax);
                                                                  ^~~~~~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBMol_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:19947:81: error: ‘class OpenBabel::OBMol’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBMol * >(argp1); result = (bool)(arg1)->IsPeriodic(); r_ans = Rf_ScalarLogical(result);
                                                                                 ^~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBMolAtomIter_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:30119:90: error: ‘class OpenBabel::OBAtom’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBMolAtomIter * >(argp1); result = (bool)(*arg1)->IsPeriodic();
                                                                                          ^~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBMolAtomDFSIter_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:31454:93: error: ‘class OpenBabel::OBAtom’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBMolAtomDFSIter * >(argp1); result = (bool)(*arg1)->IsPeriodic();
                                                                                             ^~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBMolAtomBFSIter_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:32795:93: error: ‘class OpenBabel::OBAtom’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBMolAtomBFSIter * >(argp1); result = (bool)(*arg1)->IsPeriodic();
                                                                                             ^~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBMolBondBFSIter_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:33550:93: error: ‘class OpenBabel::OBBond’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBMolBondBFSIter * >(argp1); result = (bool)(*arg1)->IsPeriodic();
                                                                                             ^~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBMolBondIter_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:34270:90: error: ‘class OpenBabel::OBBond’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBMolBondIter * >(argp1); result = (bool)(*arg1)->IsPeriodic();
                                                                                          ^~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBAtomAtomIter_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:35544:91: error: ‘class OpenBabel::OBAtom’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBAtomAtomIter * >(argp1); result = (bool)(*arg1)->IsPeriodic();
                                                                                           ^~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBAtomBondIter_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:36302:91: error: ‘class OpenBabel::OBBond’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBAtomBondIter * >(argp1); result = (bool)(*arg1)->IsPeriodic();
                                                                                           ^~~~~~~~~~
ChemmineOB.cpp: In function ‘SEXPREC* R_swig_OBResidueAtomIter_IsPeriodic(SEXP, SEXP)’:
ChemmineOB.cpp:38237:94: error: ‘class OpenBabel::OBAtom’ has no member named ‘IsPeriodic’
    arg1 = reinterpret_cast< OpenBabel::OBResidueAtomIter * >(argp1); result = (bool)(*arg1)->IsPeriodic();
                                                                                              ^~~~~~~~~~
/usr/lib/R/etc/Makeconf:177: recipe for target 'ChemmineOB.o' failed
make: *** [ChemmineOB.o] Error 1
ERROR: compilation failed for package ‘ChemmineOB’
* removing ‘/home/sukis/R/x86_64-pc-linux-gnu-library/3.6/ChemmineOB’

there is openbabel folder inside lib though, it contains only 3.0.0 folder which includes various files. should i use /usr/local/lib/openbabel/3.0.0 instead?
![image](https://user-images.githubusercontent.com/55191839/80022652-ad192800-84dc-11ea-8253-d486639aff4d.png)

moreover, the include folder is like below:
![image](https://user-images.githubusercontent.com/55191839/80023083-49dbc580-84dd-11ea-9fc0-1adde4f9d18c.png)

**Comment by khoran** [comment]
Looks like you've uncovered a mistake I made. The functions it's complaining about not existing really don't exist in the 3.0.0 version of openbabel. They do exist in the master (development) branch of OpenBabel though. So I'm pretty sure what happened is that during my last build, I forgot to checkout the correct branch of openbabel and left it on master instead. 

I'll have to rebuild the whole package. I may get to it today, but if not I won't be able to fix it until next week. 

Sorry about that. Thanks for being a beta tester for me! I think you're the first one to use this new version.

**Comment by Sukis123** [comment]
It doesn't matter. Anyway, thanks a lot for your effort to develop and maintain the package.

**Comment by khoran** [comment]
I've deployed a new version, you can find it here: https://github.com/girke-lab/ChemmineOB/releases/tag/1.25.2

You should be able to leave your openbabel installation as-is. It would actually be helpful to me  know if it will work for you. Thanks.

**Comment by Sukis123** [comment]
I have tried the new package. 
when installing the package from .tar.gz in R, i still have the same fatal error: openbabel/obutil.h: No such file or directory;
while installing it in bash using "R CMD INSTALL --configure-args='--with-openbabel-include=/usr/local/include/openbabel3/ --with-openbabel-lib=/usr/local/lib ' ChemmineOB_1.25.2.tar.gz", I got the following error:

* installing to library ‘/home/sukis/R/x86_64-pc-linux-gnu-library/3.6’
* installing *source* package ‘ChemmineOB’ ...
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/sukis/R/x86_64-pc-linux-gnu-library/3.6/BH/include" -I"/home/sukis/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"  -I/usr/local/include/openbabel3/  -I/usr/include/eigen3  -DUSE_BOOST -DHAVE_EIGEN -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-V28x5H/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ChemmineOB.cpp -o ChemmineOB.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/sukis/R/x86_64-pc-linux-gnu-library/3.6/BH/include" -I"/home/sukis/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"  -I/usr/local/include/openbabel3/  -I/usr/include/eigen3  -DUSE_BOOST -DHAVE_EIGEN -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-V28x5H/r-base-3.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c canonical.cpp -o canonical.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o ChemmineOB.so ChemmineOB.o canonical.o -L/usr/local/lib -lopenbabel -L/usr/lib/R/lib -lR
installing to /home/sukis/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-ChemmineOB/00new/ChemmineOB/libs
** R
** inst
** byte-compile and prepare package for lazy loading
in method for ‘copyToR’ with signature ‘"_p_std::char_traits<(char)>"’: no definition for class “_p_std::char_traits<(char)>”
in method for ‘copyToR’ with signature ‘"_p_std::pair<(unsigned int,unsigned int)>"’: no definition for class “_p_std::pair<(unsigned int,unsigned int)>”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::CharPtrLess"’: no definition for class “_p_OpenBabel::CharPtrLess”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::FptIndexHeader"’: no definition for class “_p_OpenBabel::FptIndexHeader”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::OBStereo"’: no definition for class “_p_OpenBabel::OBStereo”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::OBStereoUnit"’: no definition for class “_p_OpenBabel::OBStereoUnit”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::LineSearchType"’: no definition for class “_p_OpenBabel::LineSearchType”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::OBTetrahedralConfig"’: no definition for class “_p_OpenBabel::OBTetrahedralConfig”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::OBCisTransConfig"’: no definition for class “_p_OpenBabel::OBCisTransConfig”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::OBSquarePlanarConfig"’: no definition for class “_p_OpenBabel::OBSquarePlanarConfig”
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘ChemmineOB’:
 .onLoad failed in loadNamespace() for 'ChemmineOB', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/sukis/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-ChemmineOB/00new/ChemmineOB/libs/ChemmineOB.so':
  libopenbabel.so.6: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/sukis/R/x86_64-pc-linux-gnu-library/3.6/ChemmineOB’

**Comment by khoran** [comment]
That is likely caused by your version of R being 3.6. The next bioconductor release will be for R 4.0.0, which this was also compiled against.  4.0.0 is still a development release, you can download it here: http://cran.r-project.org/src/base-prerelease

**Comment by Sukis123** [comment]
How can I install this development version in Linux?

**Comment by khoran** [comment]
From the link in my last post, download R-devel.tar.gz and unpack it. 

You can find build instructions here: https://cloud.r-project.org/bin/linux/debian/#installing-r-devel-or-a-release-branch-from-svn

I think its basically just `.configure`, `make`, `make install` though.

**Comment by Sukis123** [comment]
Ok, I will try, many thanks.

**Comment by khoran** [comment]
Where you able to get ChemmineOB 1.25.2 working in the end?
